---
collections:
- name: awx.awx
  source: "https://galaxy123.ansible.com"
  #- git@github.com:dudecole/ah_configuration.git
  #- redhat_cop.controller_configuration
  #- servicenow.itsm
  #- community.general
  #- community.crypto
  #- community.postgresql
  #- servicenow.servicenow
  #  ansible.automation_platform_installer
  #- name: ansible.posix
  #- name: pulp.pulp_installer
  #- name: redhat_cop.controller_configuration
