---
collections:
- git@github.com:dudecole/ah_configuration.git

  #- redhat_cop.controller_configuration
  #- servicenow.itsm
  #- servicenow.servicenow
  #- redhat_cop.controller_configuration
  #- redhat_cop.ah_configuration
  #- servicenow.itsm
  #- awx.awx
  #- community.general
  #- community.crypto
  #- community.postgresql
  #  ansible.automation_platform_installer
  #- name: ansible.posix
  #- name: pulp.pulp_installer
  #- name: redhat_cop.controller_configuration
