---
collections:
  - name: ansible.posix 
  - name: awx.awx 
  - name: ansible.automation_platform_installer
  - name: community.general
  - name: community.crypto
  - name: community.postgresql
  - name: mdellweg.filters
  - name: pulp.pulp_installer
