---
collections:
  #  ansible.automation_platform_installer
  #- name: ansible.posix
  #- name: awx.awx
  #- name: community.general
  #- name: community.crypto
  #- name: community.postgresql
  #- name: pulp.pulp_installer
  #- name: redhat_cop.controller_configuration
