---
- name: Open up permissions on nginx.
  seboolean:
    name: '{{item}}'
    persistent: yes
    state: 'true'
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
  with_items:
    - httpd_can_network_connect

- name: Copy user-provided SSL certificates, if we have them
  when: web_server_ssl_cert is defined
  block:

    - name: Copy SSL certificate
      copy:
        src: "{{ web_server_ssl_cert }}"
        dest: /etc/tower/tower.cert
        owner: root
        group: awx
        mode: 0600
      notify:
        - reload nginx

    - name: Copy SSL private key
      copy:
        src: "{{ web_server_ssl_key }}"
        dest: /etc/tower/tower.key
        owner: root
        group: awx
        mode: 0600
      notify:
        - reload nginx

- name: Use internal CA
  include_role:
    name: certificate_authority
    tasks_from: sign_service.yml
  vars:
    aap_ca_servicename: automationcontroller
    aap_service_owner: root
    aap_service_group: awx
    aap_service_cert_path: '/etc/tower'
    aap_service_cert_name: 'tower'
    aap_service_cert_extension: 'cert'
  when:
    - web_server_ssl_cert is not defined

- name: Trigger nginx notifier for internally managed certificate changes
  debug:
    msg: 'Restart for nginx triggered due to internally managed certificate pair change.'
  changed_when: True
  when: aap_service_webserver_restart | default(False)
  notify:
    - reload nginx

- name: Install nginx.conf
  template:
    src: nginx.conf
    dest: '/etc/nginx/nginx.conf'
    force: True
    owner: root
    group: root
    validate: nginx -t -c %s
  notify:
    - restart nginx

- name: start nginx and configure to startup automatically
  service:
    name: nginx
    state: started
    enabled: yes

- set_fact:
    controller_url_port: "{{ ':' + (_nginx_http_port|string if _nginx_disable_https | bool else _nginx_https_port|string) }}"
  when: (_nginx_disable_https | bool and _nginx_http_port|string != '80') or (not _nginx_disable_https | bool and _nginx_https_port|string != '443')

- set_fact:
    controller_base_url: "{{ ('http' if _nginx_disable_https | bool else 'https') + '://' + ansible_host | default(inventory_hostname) + controller_url_port | default('') }}"
