---
- hosts: all

  vars:
    nfs_shared_volume_setup: "/ansible/aap-setup"
    runner_path: "/runner/project"
    setup_file: "setup.sh"
    setup_path: "{{ nfs_shared_volume_setup }}/{{ setup_file }}"
    inventory_file_name: "inventory"
    inventory_file_path: "{{ runner_path }}/{{ inventory_file_name }}"
    inventory_contents: "{{ lookup('file', inventory_file_name) }}"
    setup_node: '192.168.56.12'
    my_contents: >-
         {{ lookup('file', inventory_file_path) }}
    file_owner: "nobody"
    group_owner: "nobody"

  tasks:
  - name: add inventory contents to the new file
    copy:
      content: "{{ my_contents }}"
      dest: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}" 
      mode: 0777
      owner: "{{ file_owner }}"
      group: "{{ group_owner }}"
    register: block_results
    become: yes
    delegate_to: "{{ setup_node }}"

  - name: echo PWD, hostname, and info about the localhost
    shell: |
      echo "PRESENT WORKING DIR"
      pwd
      echo "List DIR"
      ls -al 
      echo "HOSTNAME"
      hostname
    register: shell_results
      #    delegate_to: "{{ setup_node }}"

      

#Next Play
#- hosts: all
#  tasks:
#  - name: run setup.sh and include new inventory file
#    shell: > 
#      {{ setup_path }} -i {{ inventory_file_path }} -- 
#      -v -e @{{ nfs_shared_volume_setup }}/creds.yml
#    register: command_results
#    async: 3600
#    poll: 60
#    delegate_to: setup_node
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"


########################        
# leaving out for now..       
#  - name: run setup.sh 
#    command: "{{ setup_path }} -i {{ base_path }}/{{ inv_file }} -- -vvv -e @{{ base_path }}/creds.yml"
#    register: command_results
#    delegate_to: "{{ controller_ip }}" 
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"

    
