---
- hosts: all

  vars:
    setup_path: /ansible/aap-setup/setup.sh
    base_path: /ansible/aap-setup
    inv_file: inventory.bak
    controller_ip: 192.168.59.10

  tasks:
  - name: ok what directory am I in.
    shell:
      cmd: |
        ls -al /ansible
    register: results

      #  - name: debug command_results
      #    debug:
      #      msg: "{{ results }}"

  - name: copy setup contents shared volume
    copy:
      src: inventory
      dest: "{{ base_path }}/{{ inv_file }}"
      mode: 0755
      owner: nobody
      group: nobody
    register: copy_results
    delegate_to: "{{ controller_ip }}" 

      #  - name: debug command_results
      #    debug:
      #      msg: "{{ copy_results }}"
      
  - name: run setup.sh 
    command: "{{ setup_path }} -i {{ base_path }}/{{ inv_file }} -- -vvv -e @{{ base_path }}/creds.yml"
    register: command_results
    delegate_to: 192.168.59.10

  - name: debug command_results
    debug:
      msg: "{{ command_results }}"

    
