---
- hosts: 192.168.59.10
  connection: local

  vars_file:
    - inventory.yml

  tasks:
    - name: run setup.sh please
      command: ./setup.sh -i inventory.yml
#"./setup.sh -i {{ tower_install_inventory }} {{ tower_install_extra_vars }} -- {{ tower_vault_params }}"
