---
- hosts: all

  vars:
    nfs_shared_volume_setup: "/ansible/aap-setup"
    setup_file: "setup.yml"
    setup_path: "{{ nfs_shared_volume_setup }}/{{ setup_file }}"
    runner_inventory: "/runner/project/inventory"
    inventory_file_name: "inventory"
    inventory_contents: |
      {{ lookup('file', runner_inventory) }}
    inventory_file_path: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}"

  tasks:
  - name: debug inventory contents
    debug:
      msg: "{{ inventory_contents }}"

  - name: loop through a number of times to create some dummy files 
    file:
      state: touch
      path: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}" 
      force: yes 
      mode: 0777
      owner: root
      group: root
    register: file_results
    become: yes
      #    delegate_to: localhost

  - name: debug the file results
    debug:
      msg: "{{ file_results }}"

  - name: add some lines to the new file
    blockinfile:
      content: "{{ inventory_contents }}"
      dest: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}" 
    register: block_results
      


  - name: run setup.sh 
    command: "{{ setup_path }} -i {{ inventory_file_path }} -- -vvv -e @{{ nfs_shared_volume_setup }}/creds.yml"
    register: command_results
      #    delegate_to: "{{ controller_ip }}" 

  - name: debug command_results
    debug:
      msg: "{{ command_results }}"


########################        
# leaving out for now..       
#  - name: run setup.sh 
#    command: "{{ setup_path }} -i {{ base_path }}/{{ inv_file }} -- -vvv -e @{{ base_path }}/creds.yml"
#    register: command_results
#    delegate_to: "{{ controller_ip }}" 
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"

    
