---
- hosts: all

  vars:
    nfs_shared_volume_setup: "/ansible/aap-setup"
    setup_file: "setup.sh"
    setup_path: "{{ nfs_shared_volume_setup }}/{{ setup_file }}"
    inventory_file_name: "inventory"
    inventory_file_path: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}"
    inventory_contents: "{{ lookup('file', inventory_file_name) }}"
    setup_node: [execution_node['192.168.56.11']]
    inventory_contents: |
      "{{ lookup('file', inventory_file_name) }}"
    file_owner: "nobody"
    group_ownwer: "nobody"

  tasks:

  - name: Create the inventory file on NFS drive 
    file:
      state: touch
      path: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}" 
      force: yes 
      mode: 0777
      owner: "{{ file_owner }}"
      group: "{{ group_owner }}"
    register: file_results
    become: yes
      #    delegate_to: localhost

  - name: add inventory contents to the new file
    blockinfile:
      content: "{{ inventory_contents }}"
      dest: "{{ nfs_shared_volume_setup }}/{{ inventory_file_name }}" 
    register: block_results
      
#  - name: run setup.sh and include new inventory file
#    shell: > 
#      {{ setup_path }} -i {{ inventory_file_path }} -- 
#      -v -e @{{ nfs_shared_volume_setup }}/creds.yml
#    register: command_results
#    async: 3600
#    poll: 60
#    delegate_to: setup_node
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"


########################        
# leaving out for now..       
#  - name: run setup.sh 
#    command: "{{ setup_path }} -i {{ base_path }}/{{ inv_file }} -- -vvv -e @{{ base_path }}/creds.yml"
#    register: command_results
#    delegate_to: "{{ controller_ip }}" 
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"

    
