# <TODO-
# - clean up this mess...
# >
# This was originally intended to be a wrapper
# for the `setup.sh` located with the AAP 
# download/bundle pack.  But that seems
# kind of stupid and instead maybe just call
# the controller collection AAP installer playbook..
# This is not complete...
#
---
#- hosts: localhost
#  connection: local

- hosts: localhost
  connection: local
  # /ansible referring to the NFS Vol mounted on the nodes who want NFS
  #  vars:
  #    setup_path: /ansible/aap-setup/setup.sh 
  #    base_path: /ansible
  #    inv_file: inventory
  #    controller_ip: 192.168.59.10
  #    nfs_shared_volume: /ansible/aap-setup

  tasks:
  - name: ok what directory am I in.
    shell: |
      echo "Starting..."
      ls -al
      echo ""
      echo "Getting the PWD now"
      cd /runner/
      pwd
      ls -al
      echo ""
      echo "Getting the /ansible contents now"
      ls -al /ansible/
      echo "WORKING DIR"
      pwd
      ls -al
    register: command_output
    delegate_to: localhost

  - name: debug command_results
    debug:
      msg: "{{ command_output }}"

  - name: pause
    pause:
      minutes: 5

        #  - name: loop through a number of times to create some dummy directories
        #    copy:
        #      src: "/runner/project/inventory"
        #      dest: "/ansible/inventory.dude" 
        #      force: yes 
        #        #    with_sequence: count=5
        #      mode: 0777
        #      owner: nobody
        #      group: nobody
        #    register: copy_results
        #    become: yes
        #    delegate_to: localhost
        #
        #  - name: debug the directory results
        #    debug:
        #      msg: "{{ copy_results }}"



#  - name: loop through a number of times to create some dummy files 
#    copy:
#      state: touch
#      path: "{{ nfs_shared_volume }}/{{ inventory_hostname }}-{{ item }}-dir/{{ inventory_hostname }}-{{ item }}.txt" 
#      force: yes 
#    with_sequence: count=5
#    register: file_results
#    become: yes

#- name: debug the file results
#  debug:
#    msg: "{{ file_results }}"

#nfs_shared_volume: "/ansible"
#
#  - name: ok what directory am I in.
#    shell: |
#      echo "Starting..."
#      ls -al
#      echo ""
#      echo "Getting the PWD now"
#      cd /runner/project
#      pwd
#      ls -al
#      echo ""
#      echo "Getting the /ansible contents now"
#      ls -al /ansible/aap-setup/
#      echo "WORKING DIR"
#      pwd
#      ls -al
#      echo "Dir contents"
#      echo "which ls and copy binary"
#      which cp
#      which ls
#      ls -al /ansible
      #      echo "Inventory File"
      #      cat "{{ inv_file }}"
      #      echo ""
      #      echo ""
      #      echo "End of Inventory file now.."
      #      echo "Changing dir to /runner/project/"
      #      cd /runner/project/
      #      pwd
      #      ls -al 
      #      cp  /runner/project/inventory /ansible/aap-setup
      #      echo "GET DIR CONTENTS NOW"
      #      ls -al
      #      echo "GET WORKING DIR"
      #      pwd
      #    register: cmd_results
      #    delegate_to: 192.168.56.11
      #    become: true
      #
      #  - name: debug command_results
      #    debug:
      #      msg: "{{ cmd_results }}"


#      copy: 
#        src: "{{ inv_file }}" #inventory (.ini or nothing)
#        dest: "{{ base_path }}/{{ inv_file }}"
#        mode: 0755
#        owner: nobody
#        group: nobody
#      register: copy_results
#      delegate_to: localhost

#
#- hosts: all
#  vars:
#    setup_path: /ansible/aap-setup/setup.sh 
#    base_path: /ansible/aap-setup
#    inv_file: inventory
#    controller_ip: 192.168.59.10
#
#  tasks:
#  - name: ok what directory am I in.
#    shell:
#      cmd: |
#        ls -al {{ base_path }}
#    register: cmd_results
#    delegate_to: localhost
#
#  - name: debug command_results
#    debug:
#      msg: "{{ cmd_results }}"


#  - name: run setup.sh 
#    command: "{{ setup_path }} -i {{ base_path }}/{{ inv_file }} -- -vvv -e @{{ base_path }}/creds.yml"
#    register: command_results
#      #    delegate_to: "{{ controller_ip }}" 
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"


        #  - name: copy setup contents from local/project dir - to NFS volume
        #    copy:
        #      src: "{{ inv_file }}" #inventory (.ini or nothing)
        #      dest: "{{ base_path }}/{{ inv_file }}"
        #      mode: 0755
        #      owner: nobody
        #      group: nobody
        #    register: copy_results
        #    delegate_to: localhost #maybe this works..?
        #    # this runs for all hosts, need to limit to first in index or something
        #
        #  - name: debug copy_results
        #    debug:
        #      msg: "{{ copy_results }}"

########################        
# leaving out for now..       
#  - name: run setup.sh 
#    command: "{{ setup_path }} -i {{ base_path }}/{{ inv_file }} -- -vvv -e @{{ base_path }}/creds.yml"
#    register: command_results
#    delegate_to: "{{ controller_ip }}" 
#
#  - name: debug command_results
#    debug:
#      msg: "{{ command_results }}"

    
