---
- hosts: localhost

  collections: 
  - dudecole.ansible_creds
  
  tasks: 
  - name: debug something..
    shell: "ls -al collections/"
    register: shell_output
    
  - name: debug shell_output
    debug:
      msg: "{{ shell_output }}"
    
  - name: pause for viewing
    pause:
      minutes: 5
      
  #- ansible.builtin.import_playbook: dudecole.ansible_creds.debug-creds

    
