---
- hosts: localhost

  collections: 
  - dudecole.ansible_creds
  
  tasks: 
  - name: debug something..
    shell: "ls -al"
    
  - name: pause for viewing
    pause:
      minutes: 5
      
  #- ansible.builtin.import_playbook: dudecole.ansible_creds.debug-creds

    
