---
- hosts: localhost

  collections: 
  - dudecole.ansible_creds
  
  tasks: 
  - name: debug something..
    shell: ls -al '{{ playbook_dir }}/../'
    register: shell_output
    
  - name: debug shell_output
    debug:
      msg: 
      - "{{ shell_output }}"
      - "{{ playbook_dir }}"
#       - "{{ collection_path }}"
          
#   - name: import collection playbook
#     import_playbook: "{{ playbook_dir }}/../requirements_collections/dudecole/ansible_creds/debug-creds"
#     register: import_output
     
#   - name: debug import_output
#     debug:
#       msg: "{{ import_output }}"

    
