---
- hosts: all
  connection: local
  
  collections: 
  - dudecole.ansible_creds
  
  tasks: 
  - name: debug the facts from the playbook in the credentials collection
    ansible.builtin.include_playbook: dudecole.ansible_creds.debug-creds.yml
    
