---
# handlers file for automationcatalog

- name: Restart automation-services-catalog
  service:
    name: "automation-services-catalog.target"
    enabled: true
    state: restarted

# Handlers for redis restart
- name: restart redis
  service:
    name: redis
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded
