---
automationcatalog_web_proto: 'https'
automationcatalog_disable_https: 'false'
automationcatalog_disable_hsts: false
automationcatalog_user_headers: []

automationcatalog_controller_verify_ssl: 'true'
automationcatalog_controller_regenerate_token: 'false'

sso_automationcatalog_client_id: automation-catalog
sso_automationcatalog_client_name: 'Automation Service Catalog'
sso_validate_certs: false
sso_automationcatalog_user_group_configuration: sso_sample_user_group.yml
sso_automationcatalog_create_user_group: true

automationcatalog_postgresql_version: '13'
automationcatalog_redis_version: '6'

automationcatalog_allowed_hostnames: []
automationcatalog_allowed_addresses:
  - "{{ ansible_all_ipv4_addresses|default([]) }}"
  - "{{ ansible_all_ipv6_addresses|default([]) }}"
