---
- name: Ensure SSO node is run on a RHEL 8 node
  fail:
    msg: '[sso] nodes must be run on RHEL 8 nodes. RHEL 9 is not supported.'
  when:
    - inventory_hostname in groups['sso'] | default([])
    - ansible_distribution_major_version == "9"

- name: Ensure expected variables are defined
  fail: msg="{{ item }} value missing and is required"
  when: hostvars[inventory_hostname][item] is not defined
  with_items: "{{ check_config_static_required_vars }}"

- name: Ensure cluster hosts are not localhost
  fail:
    msg: "'localhost' is not allowed as a target host for cluster installs. Use the hostname or address instead (ansible_connection=local can still be used)"
  when:
    - groups['automationcontroller'] | default([]) | length > 1
    - ansible_host is match("127.*") or ansible_host is match("localhost*") or ansible_host == "::1"

- name: Check that group names do not conflict with instance names
  fail: msg="Hostname '{{ ansible_host }}' conflicts with the name of a group"
  when: ('instance_group_' + ansible_host) in groups

- name: Perform inventory sanity checks
  run_once: True
  delegate_to: localhost
  block:

    - name: Detect pre-2.x inventory and offer a migration
      upgrade_isolated_inventory:

    - name: Detect unsupported HA inventory file
      fail:
        msg: 'Detected an unsupported HA inventory file, please consult the documentation and update the inventory file accordingly.'
      when: "'primary' in groups or 'secondary' in groups"

    - name: Check that no instance groups are named automationcontroller
      fail: msg="Cannot name instance group automationcontroller"
      with_items: "{{ groups }}"
      when:
        - item != "automationcontroller"
        - item.replace('instance_group_', '') == "automationcontroller"

    - name: Ensure only one database host exists
      fail:
        msg: "One, and only one, database host may be specified. Database group hosts {{ groups['database'] }}"
      when:
        - groups['database'] | default([]) | length > 1

    - name: Ensure automationhub_pg related variables are defined if more than one component is enabled
      fail:
        msg: "automationhub_pg_host is currently empty, ensure automationhub_pg_host is defined and pointing to a database."
      when:
        - groups['automationhub'] | default([]) | length
        - groups['automationcatalog'] | default([]) | length or groups['automationcontroller'] | default([]) | length
        - not automationhub_pg_host | default('') | length

    - name: Ensure automationcatalog_pg related variables are defined if more than one component is enabled
      fail:
        msg: "automationcatalog_pg_host is currently empty, ensure automationcatalog_pg_host is defined and pointing to a database."
      when:
        - groups['automationcatalog'] | default([]) | length
        - groups['automationhub'] | default([]) | length or groups['automationcontroller'] | default([]) | length
        - not automationcatalog_pg_host | default('') | length

    - name: Preflight check - Fail if Automation Controller host is localhost
      fail:
        msg: "The host specified in the [automationcontroller] group in your inventory file cannot be localhost. Please update your inventory file properly."
      with_items: "{{ groups['automationcontroller'] | default([]) }}"
      when: item is match("127.*") or item is match("localhost*") or item == "::1"

    - name: Preflight check - Fail if Automation Hub host is localhost
      fail:
        msg: "The host specified in the [automationhub] group in your inventory file cannot be localhost because the resulting hub node's content URL will not be reachable by the controller node."
      with_items: "{{ groups['automationhub'] | default([]) }}"
      when: item is match("127.*") or item is match("localhost*") or item == "::1"

    - name: Preflight check - Fail if Automation Services Catalog host is localhost
      fail:
        msg: "The host specified in the [automationcatalog] group in your inventory file cannot be localhost"
      with_items: "{{ groups['automationcatalog'] | default([]) }}"
      when: item is match("127.*") or item is match("localhost*") or item == "::1"

    - name: Ensure hub, catalog, and controller are installed on different nodes
      fail:
        msg: "Hub can not be installed on a controller node. Please update your inventory."
      when:
        - groups['automationhub'] | default([]) | length
        - groups['automationcontroller'] | default([]) | length
        - (groups['automationhub'][0] in groups['automationcontroller'] or hostvars[groups['automationhub'][0]]['ansible_host'] | default('') in controller_hosts_in_inventory)
      vars:
        controller_ansible_hosts: '{{ hostvars | dictsort | selectattr("1.ansible_host", "defined") | selectattr("0", "in", groups["automationcontroller"]) | map(attribute="1.ansible_host") | list }}'
        controller_inventory_hostnames: '{{ hostvars | dictsort | rejectattr("1.ansible_host", "defined") | selectattr("0", "in", groups["automationcontroller"]) | map(attribute="0") | list }}'
        controller_hosts_in_inventory: '{{ controller_ansible_hosts + controller_inventory_hostnames }}'

    - name: Ensure when postgres host is defined that the port is defined
      fail: msg="pg_host variable defined but pg_port is not defined. Please define it."
      when: "pg_host is defined and pg_port is not defined"

    - name: Ensure that when a database host is specified, that pg_host, automationhub_pg_host, or automationcatalog_pg_host is defined
      fail:
        msg: "pg_host, automationhub_pg_host, or automationcatalog_pg_host is required when hosts in the database group exist."
      when:
        - groups['database'] | default([]) | length
        - ((groups['automationcontroller'] | default([]) | length and not pg_host | default('') | length) or (groups['automationhub'] | default([]) | length and not automationhub_pg_host | default('') | length)or (groups['automationcatalog'] | default([]) | length and not automationcatalog_pg_host | default('') | length))

    - name: Ensure that when a database host is specified, that pg_port, automationhub_pg_port, or automationcatalog_pg_port is defined
      fail:
        msg: "pg_port, automationhub_pg_port, or automationcatalog_pg_port is required when hosts in the database group exist."
      when:
        - groups['database'] | default([]) | length
        - ((groups['automationcontroller'] | default([]) | length and not pg_port | default(0) | int) or (groups['automationhub'] | default([]) | length and not automationhub_pg_port | default(0) | int) or (groups['automationcatalog'] | default([]) | length and not automationcatalog_pg_port | default(0) | int))

    - name: Ensure that pg_hashed_password is not set
      fail:
        msg: "pg_hashed_password no longer needs to be set in the inventory file.  The more secure SCRAM-SHA-256 hash will be used instead by default."
      when: "pg_hashed_password is defined"

    - name: Ensure that if we have web cert, we also have key
      fail:
        msg: "If you give one of web_server_ssl_cert and web_server_ssl_key, you must also give the other."
      when: "(web_server_ssl_cert is defined and web_server_ssl_key is not defined) or (web_server_ssl_key is defined and web_server_ssl_cert is not defined)"

    - name: Preflight check - verify aap_ca_server_hostname is one of the platform components
      fail:
        msg: "The Internal CA managed by Ansible Automation Platform does not require another server and must reside on one of the component servers."
      when:
        - aap_ca_server_hostname is defined
        - aap_ca_server_hostname not in ((groups['automationcontroller']  | default([])) + (groups['automationhub']  | default([])) + (groups['automationcatalog'] | default([])))

    - name: HA mode requires an external postgres database with pg_host defined
      fail:
        msg: "pg_host must be defined when multiple hosts exists"
      when:
        - groups['automationcontroller'] | default([]) | length > 1
        - not pg_host | default('') | length

    - name: HA mode requires an external postgres database with pg_port defined
      fail:
        msg: "pg_port must be defined when multiple hosts exists"
      when:
        - groups['automationcontroller'] | default([]) | length > 1
        - not pg_port | default(0) | int

    - name: Hub HA mode requires an external postgres database with automationhub_pg_host defined
      fail:
        msg: "automationhub_pg_host must be defined when multiple hosts exists"
      when:
        - groups['automationhub'] | default([]) | length > 1
        - not automationhub_pg_host | default('') | length

    - name: Hub HA mode requires an external postgres database with automationhub_pg_port defined
      fail:
        msg: "automationhub_pg_port must be defined when multiple hosts exists"
      when:
        - groups['automationhub'] | default([]) | length > 1
        - not automationhub_pg_port | default(0) | int

    - block:
        - name: Warn if automationhub_main_url is not set in Hub HA mode and using SSO
          fail:
            msg: "automationhub_main_url is not defined, the first node in [automationhub] group will be used for Single Sign-On configuration."
          ignore_errors: true

        - name: Pause for warning
          pause:
            seconds: 5
      when:
        - groups['automationhub'] | default([]) | length > 1
        - not automationhub_main_url | default('') | length
        - groups['sso'] | default([]) | length or sso_host | default('') | length

    - name: Ensure registry_username and registry_password are set for registry.redhat.io
      fail:
        msg: 'registry_username and registry_password must be set when registry_url is registry.redhat.io'
      when:
        - groups['automationcontroller'] | default([]) | length or groups['automationhub'] | default([]) | length
        - _registry_url == 'registry.redhat.io'
        - not registry_username | default('') | length or not registry_password | default('') | length
        - not bundle_install | default(false) | bool

    - name: Ensure only one SSO host exists
      fail:
        msg: "One, and only one, SSO host may be specified. SSO group hosts {{ groups['sso'] }}"
      when:
        - groups['sso'] | default([]) | length > 1

    - name: Ensure sso_host is not defined when setting up a new SSO node
      fail:
        msg: 'sso_host must not be set when setting up a new SSO node'
      when:
        - groups['sso'] | default([]) | length
        - sso_host | default('') | length

    - name: Ensure password is set for SSO
      fail:
        msg: 'sso_console_admin_password must be set'
      when:
        - groups['sso'] | default([]) | length or sso_host | default('') | length
        - not sso_console_admin_password | default('') | length

    - name: Ensure sso_keystore_password is set when enabling SSL for SSO
      fail:
        msg: "sso_keystore_password (minimum 6 characters) must be set when installing Single Sign-On with SSL support"
      when:
        - groups['sso'] | default([]) | length
        - sso_use_https | default(True) | bool
        - sso_keystore_password | default('') | length < 6

    - name: Ensure SSO host exists for Catalog
      fail:
        msg: "Host must exist in [sso] group or sso_host must be set when setting up Automation Catalog"
      when:
        - groups['automationcatalog'] | default([]) | length
        - not groups['sso'] | default([]) | length
        - not sso_host | default('') | length

    - name: Ensure Controller host exists for Catalog
      fail:
        msg: "A Automation Controller host is required for Automation Services Catalog. A host must exist in [automationcontroller] group or automation_controller_main_url must be set when setting up Automation Catalog"
      when:
        - groups['automationcatalog'] | default([]) | length
        - not groups['automationcontroller'] | default([]) | length
        - not automation_controller_main_url | default('') | length

    - name: Ensure Credentials or Token Provided with automation_controller_main_url for Catalog
      fail:
        msg: "Either automationcatalog_controller_username or automationcatalog_controller_token has to be provided when automation_controller_main_url"
      when:
        - automation_controller_main_url | default('') | length
        - not automationcatalog_controller_username | default('') | length
        - not automationcatalog_controller_token | default('') | length

    - name: Ensure that a password is provided if automationcatalog_controller_username is defined
      fail:
        msg: "A password using the variable automationcatalog_controller_password must be provided for the user defined with automationcatalog_controller_username"
      when:
        - automationcatalog_controller_username | default('') | length
        - not automationcatalog_controller_password | default('') | length

    - name: User Access Check - Automation Service Catalog to Automation Controller API
      uri:
        url: '{{ automation_controller_main_url }}/api/v2/me/'
        user: '{{ automationcatalog_controller_username }}'
        password: '{{ automationcatalog_controller_password }}'
        force_basic_auth: true
        follow_redirects: true
        validate_certs: '{{ automationcatalog_controller_verify_ssl | default(true) | bool }}'
      delegate_to: "{{ groups['automationcatalog'][0] }}"
      when:
        - groups['automationcatalog'] | default([]) | length
        - automation_controller_main_url | default('') | length
        - automationcatalog_controller_username | default('') | length
        - automationcatalog_controller_password | default('') | length
      register: _automationcatalog_controller_api_user_check
      ignore_errors: yes

    - name: Token Access Check - Automation Service Catalog to Automation Controller API
      uri:
        url: '{{ automation_controller_main_url }}/api/v2/me/'
        headers:
          Authorization: "Bearer {{ automationcatalog_controller_token }}"
          Content-Type: "application/json"
        follow_redirects: all
        validate_certs: '{{ automationcatalog_controller_verify_ssl | default(true) | bool }}'
      delegate_to: "{{ groups['automationcatalog'][0] }}"
      when:
        - groups['automationcatalog'] | default([]) | length
        - automation_controller_main_url | default('') | length
        - automationcatalog_controller_token | default('') | length
      register: _automationcatalog_controller_api_token_check
      ignore_errors: yes

    - name: Ensure Automation Service Catalog connection to Automation Controller API exists if using user credentials
      fail:
        msg: "Automation Services Catalog requires access to the provided Automation Controller's API when the automationcatalog_main_url is in inventory with automationcatalog_controller_username and automationcatalog_controller_password. Please re-run setup.sh after fixing the credential variables and access to the host."
      when:
        - automationcatalog_controller_username | default('') | length
        - automationcatalog_controller_password | default('') | length
        - _automationcatalog_controller_api_user_check is defined
        - _automationcatalog_controller_api_user_check is failed

    - name: Ensure Automation Service Catalog connection to Automation Controller API exists if using a token
      fail:
        msg: "Automation Services Catalog requires access to the provided Automation Controller's API when the automationcatalog_main_url is in inventory with automationcatalog_controller_token. Please re-run setup.sh after fixing the credential variables and access to the host."
      when:
        - automationcatalog_controller_token | default('') | length
        - _automationcatalog_controller_api_token_check is defined
        - _automationcatalog_controller_api_token_check is failed

    - name: Ensure that Automation Hub signing script and signing keys are provided when signing is enabled
      fail:
        msg: "Automation Hub is configured to enable a signing service. But one of automationhub_collection_signing_service_key or automationhub_collection_signing_service_script has not been specified. Both are mandatory when signing is enabled."
      when:
        - groups['automationhub'] | default([]) | length
        - automationhub_create_default_collection_signing_service | default(false) | bool
        - not automationhub_collection_signing_service_key | default('') | length
        - not automationhub_collection_signing_service_script | default('') | length
