---
- name: Restart pulpcore-api.service
  systemd:
    name: pulpcore-api.service
    enabled: true
    state: restarted
  become: true

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: true
  become: true
