---
- name: Check for old PostgreSQL data
  stat:
    path: "{{ existing_pg_dir }}/PG_VERSION"
  register: old_pg_version_file

- name: Read PG_VERSION file contents
  command: "cat {{ existing_pg_dir }}/PG_VERSION"
  register: old_pg_version_file_content
  when: old_pg_version_file.stat.exists

- name: Check if PostgreSQL has already been upgraded
  stat:
    path: "{{ existing_pg_dir }}/PG_VERSION.upgraded13"
  register: pg_already_upgraded

- name: Check if PostgreSQL has already been upgraded
  stat:
    path: "{{ existing_pg_dir }}/PG_VERSION.upgraded12"
  register: pg_12_already_upgraded

- name: Determine if PostgreSQL 10 is present
  set_fact:
    upgrade_from_postgres_10: >-
      {{ (old_pg_version_file.stat.exists and
          ((old_pg_version_file_content.stdout | trim | int) == 10) and
          (not pg_12_already_upgraded.stat.exists) | bool) }}

- name: Determine if we should upgrade PostgreSQL
  set_fact:
    upgrade_postgres: >-
      {{ (old_pg_version_file.stat.exists and
          ((old_pg_version_file_content.stdout | trim | int) != 13) and
          (not pg_already_upgraded.stat.exists) | bool) }}

- block:
    - name: Uninstall PostgreSQL 12 Client
      shell: |
        dnf module -y reset 'postgresql'
      args:
        warn: false

    - name: Enable PostgreSQL 13 dnf modules
      shell: |
        dnf module -y enable 'postgresql:13'
      args:
        warn: false

    - name: Install PostgreSQL
      dnf:
        name: '@postgresql:13/server'
        state: present
  when:
    - not upgrade_postgres | bool
    - not upgrade_from_postgres_10 | bool
    - ansible_distribution_major_version == "8"

- name: Install PostgreSQL
  dnf:
    name: 'postgresql-server'
    state: present
  when: ansible_distribution_major_version == "9"

- name: Upgrade PostgreSQL data from 10 --> 12
  include_tasks: upgrade_from_postgres_10.yml
  when:
    - upgrade_from_postgres_10 | bool
    - ansible_distribution_major_version == "8"

- name: Upgrade PostgreSQL
  include_tasks: upgrade_postgres.yml
  when:
    - upgrade_postgres | bool
    - ansible_distribution_major_version == "8"
