---
# Tasks to install required packages for EL distros
- name: Install playbook dependencies
  yum:
    name: '{{ el_dependencies }}'
    state: present


- block:

  - name: Disable required dnf modules
    shell: |
      dnf module -y disable {{ item }}
    args:
      warn: false
    with_items: "{{ dnf_modules_disable }}"

  - name: Enable required dnf modules
    shell: |
      dnf module -y reset {{ item }} && dnf module -y enable {{ item }}
    args:
      warn: false
    with_items: "{{ dnf_modules }}"

  - block:
    - name: Enable required nginx dnf modules
      shell: |
        dnf module -y reset nginx && dnf module -y enable nginx:1.20
      args:
        warn: false

    rescue:
    - name: Enable required dnf modules
      shell: |
        dnf module -y reset nginx && dnf module -y enable nginx:1.18
      args:
        warn: false

  when: ansible_distribution_major_version == "8"
