---
- block:
  - name: Append .gz to database archive filename if use_compression
    set_fact:
      db_filename: tower.db.gz
    when: (use_compression | bool)

  - name: Cleanup common backup directory
    file:
      path: '{{ backup_dir.rstrip("/") }}/common/'
      state: absent

  - name: Copy temporary sql files
    copy:
      src: '{{ item }}'
      dest: '{{ backup_dir.rstrip("/") }}/common/'
      owner: root
      mode: '0600'
    with_items:
      - instance_group_map.sql
      - instance_group_map_cleanup.sql

  - name: Create (temporary) mapping between instance group ids / names
    shell: |
      psql \
        --host='{{ controller_db_settings.default.HOST }}' \
        --port='{{ controller_db_settings.default.PORT }}' \
        --username='{{ controller_db_settings.default.USER  }}' \
        --dbname='{{ controller_db_settings.default.NAME }}' < instance_group_map.sql
    args:
      chdir: '{{ backup_dir.rstrip("/") }}/common/'
    environment: "{{ {'PGPASSWORD': controller_db_settings.default.PASSWORD} | combine( extra_env | default({}) ) }}"
    register: psql_command
    failed_when: "'ERROR' in psql_command.stderr"
    no_log: True

  - name: Pre-create database dump to establish permissions
    file:
      path: '{{ backup_dir.rstrip("/") }}/common/{{ db_filename }}'
      owner: root
      mode: '0600'
      state: touch

  # clean drops the database
  # create adds instructions to create the database
  # Note: user needs access to postgres template when restoring
  - name: Perform a PostgreSQL dump.
    shell: |
      pg_dump \
        --clean --create \
        --host='{{ controller_db_settings.default.HOST }}' \
        --port={{ controller_db_settings.default.PORT }} \
        --username='{{ controller_db_settings.default.USER  }}' \
        --dbname='{{ controller_db_settings.default.NAME }}' \
        --exclude-table=main_instance \
        --exclude-table=main_instancegroup \
        --exclude-table=main_instancegroup_instances \
        {{ '| gzip' if use_compression | bool else '' }} > {{ db_filename }}
    args:
      chdir: '{{ backup_dir.rstrip("/") }}/common/'
    environment: "{{ {'PGPASSWORD': controller_db_settings.default.PASSWORD} | combine( extra_env | default({}) ) }}"
    register: psql_command
    failed_when: "'ERROR' in psql_command.stderr"
    no_log: True

  - name: Make sure PostgreSQL dump has the right permissions
    file:
      path: '{{ backup_dir.rstrip("/") }}/common/{{ db_filename }}'
      owner: root
      mode: '0600'
      state: file

  - name: Remove mapping between instance group ids / names
    shell: |
      psql \
        --host='{{ controller_db_settings.default.HOST }}' \
        --port={{ controller_db_settings.default.PORT }} \
        --username='{{ controller_db_settings.default.USER  }}' \
        --dbname='{{ controller_db_settings.default.NAME }}' < instance_group_map_cleanup.sql
    args:
      chdir: '{{ backup_dir.rstrip("/") }}/common/'
    environment: "{{ {'PGPASSWORD': controller_db_settings.default.PASSWORD} | combine( extra_env | default({}) ) }}"
    register: psql_command
    failed_when: "'ERROR' in psql_command.stderr"
    no_log: True

  - name: Remove temporary sql files
    file:
      path: '{{ backup_dir.rstrip("/") }}/common/{{ item }}'
      state: absent
    with_items:
      - instance_group_map.sql
      - instance_group_map_cleanup.sql

  when:
    - groups['automationcontroller'] | default([]) | length
    - inventory_hostname == groups['automationcontroller'][0]

- block:
    - name: Pre-create database dump to establish permissions
      file:
        path: '{{ backup_dir.rstrip("/") }}/automationhub/automationhub/automationhub.db'
        owner: root
        mode: '0600'
        state: touch

    - name: Perform a PostgreSQL dump.
      shell: |
        pg_dump \
          --clean --create \
          --host='{{ automationhub_db_settings.default.HOST }}' \
          --port={{ automationhub_db_settings.default.PORT }} \
          --username='{{ automationhub_db_settings.default.USER  }}' \
          --dbname='{{ automationhub_db_settings.default.NAME }}' > automationhub.db
      args:
        chdir: '{{ backup_dir.rstrip("/") }}/automationhub/automationhub'
      environment: "{{ {'PGPASSWORD': automationhub_db_settings.default.PASSWORD} | combine( extra_env | default({}) ) }}"
      register: psql_command
      failed_when: "'ERROR' in psql_command.stderr"

    - name: Make sure PostgreSQL dump has the right permissions
      file:
        path: '{{ backup_dir.rstrip("/") }}/automationhub/automationhub/automationhub.db'
        owner: root
        mode: '0600'
        state: file

  when:
    - inventory_hostname in groups['automationhub'] | default([])

- block:
    - name: Pre-create database dump to establish permissions
      file:
        path: '{{ backup_dir.rstrip("/") }}/automationcatalog/automationcatalog/automationcatalog.db'
        owner: root
        mode: '0600'
        state: touch

    - name: Perform a PostgreSQL dump.
      postgresql_db:
        name: '{{ automationcatalog_db_settings.name }}'
        login_host: '{{ automationcatalog_db_settings.host }}'
        login_port: '{{ automationcatalog_db_settings.port }}'
        login_user: '{{ automationcatalog_db_settings.user }}'
        login_password: '{{ automationcatalog_db_settings.password }}'
        target: '{{ backup_dir.rstrip("/") }}/automationcatalog/automationcatalog/automationcatalog.db'
        target_opts: '--clean --create'
        state: dump
      environment: '{{ extra_env | default(omit) }}'

    - name: Make sure PostgreSQL dump has the right permissions
      file:
        path: '{{ backup_dir.rstrip("/") }}/automationcatalog/automationcatalog/automationcatalog.db'
        owner: root
        mode: '0600'
        state: file

  when:
    - inventory_hostname in groups['automationcatalog'] | default([])
