---
- name: Copy user-provided SSL certificates
  when: automationcatalog_ssl_cert is defined
  block:

    - name: Copy SSL certificate
      copy:
        src: "{{ automationcatalog_ssl_cert }}"
        dest: /etc/ansible-automation-platform/services-catalog/server.cert
        owner: root
        group: pinakes
        mode: 0600
      notify:
        - reload nginx

    - name: Copy SSL private key
      copy:
        src: "{{ automationcatalog_ssl_key }}"
        dest: /etc/ansible-automation-platform/services-catalog/server.key
        owner: root
        group: pinakes
        mode: 0600
      notify:
        - reload nginx

- name: Use internal CA
  include_role:
    name: certificate_authority
    tasks_from: sign_service.yml
  vars:
    aap_ca_servicename: automationcatalog
    aap_service_owner: root
    aap_service_group: pinakes
    aap_service_cert_path: '/etc/ansible-automation-platform/services-catalog'
    aap_service_cert_name: 'server'
    aap_service_cert_extension: 'cert'
  when:
    - automationcatalog_ssl_cert is not defined

- name: Trigger nginx notifier for internally managed certificate changes
  debug:
    msg: 'Restart for nginx triggered due to internally managed certificate pair change.'
  changed_when: True
  notify:
    - reload nginx
  when: aap_service_webserver_restart | default(False)
